postgres: start WAL location info embedded in full backup folder name

diff --git a/postgres/templates/configmaps.yaml b/postgres/templates/configmaps.yaml
--- a/postgres/templates/configmaps.yaml
+++ b/postgres/templates/configmaps.yaml
@@ -18,7 +18,7 @@ data:
     LABEL=""
     if [ "$EMPTY" != "yes" ]
     then
-      LABEL="$(rclone lsf "rem:${DNAME}" | sort -r | awk -F '/' '/^\d{8}-\d{6}\/$/ { print $1 ; exit 0 ; }')"
+      LABEL="$(rclone lsf "rem:${DNAME}" | sort -r | awk -F '/' '/^[0-9]{8}-[0-9]{6}-[0-9A-F]{24}\/$/ { print $1 ; exit 0 ; }')"
     fi
     date
     if [ "$LABEL" != "" ]
@@ -67,7 +67,14 @@ data:
     date
     pg_verifybackup -nP "/loc/${LABEL}"
     date
-    rclone copyto -P "/loc/${LABEL}" "rem:${DNAME}/${LABEL}"
+    START_WAL_LOCATION="$(tar xzf "/loc/${LABEL}/base.tar.gz" -O backup_label | awk '/^START WAL LOCATION:/ { print substr($6,1,24) }')"
+    if [ "${#START_WAL_LOCATION}" != "24" ]
+    then
+      echo "error: wrong '${START_WAL_LOCATION}' (length is not 24)"
+      exit 1
+    fi
+    date
+    rclone copyto -P "/loc/${LABEL}" "rem:${DNAME}/${LABEL}-${START_WAL_LOCATION}"
     date
 
 ---
