postgres: WALs older than first full backup are deleted by cleanup process

diff --git a/postgres/templates/configmaps.yaml b/postgres/templates/configmaps.yaml
--- a/postgres/templates/configmaps.yaml
+++ b/postgres/templates/configmaps.yaml
@@ -70,12 +70,20 @@ data:
     START_WAL_LOCATION="$(tar xzf "/loc/${LABEL}/base.tar.gz" -O backup_label | awk '/^START WAL LOCATION:/ { print substr($6,1,24) }')"
     if [ "${#START_WAL_LOCATION}" != "24" ]
     then
-      echo "error: wrong '${START_WAL_LOCATION}' (length is not 24)"
+      echo "error: wrong START_WAL_LOCATION='${START_WAL_LOCATION}' (length is not 24)"
       exit 1
     fi
     date
     rclone copyto -P "/loc/${LABEL}" "rem:${DNAME}/${LABEL}-${START_WAL_LOCATION}"
     date
+    # cleanup
+    WAL_MIN="$(rclone lsf "rem:${DNAME}" | sort | awk -F '/' '/^[0-9]{8}-[0-9]{6}-[0-9A-F]{24}\/$/ { print substr($1,17) ; exit 0 ; }')"
+    if [ "${#WAL_MIN}" != "24" ]
+    then
+      echo "notice: cannot use WAL_MIN='${WAL_MIN}' (length is not 24)"
+      exit 0
+    fi
+    rclone lsf rem:pg_wal | awk -v WAL_MIN="${WAL_MIN}" -F '/' '/^[0-9A-F]{24}\..*gz$/ { if ( substr($1,1,24) < WAL_MIN ) { printf "rclone -v delete rem:pg_wal/%s\n",$1 } }' | sh -x -e -o pipefail
 
 ---
 
